### ISSUE TITLE
Switch to akka typed

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/simona#48]
The current implementation relies on akka classic which does not include type safety for message passing between actors. In the mid-term it would be very helpful to have akka typed support in order to have a more safe and stable protocol handling. This also might require some protocol adaptions and it may be helpful to have a documentation of the existing protocols available beforehand.

**Tasks**

- [ ] add documentation for existing agent and actor communication protocols
- [ ] adapt existing protocols for akka typed
- [ ] adapt the code to support akka typed

**Comment by staudtMarius** [comment]
See #1389.
